export default{
"login": "roney1001",
"id": 57011885,
"node_id": "MDQ6VXNlcjU3MDExODg1",
"avatar_url": "https://avatars.githubusercontent.com/u/57011885?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/roney1001",
"html_url": "https://github.com/roney1001",
"followers_url": "https://api.github.com/users/roney1001/followers",
"following_url": "https://api.github.com/users/roney1001/following{/other_user}",
"gists_url": "https://api.github.com/users/roney1001/gists{/gist_id}",
"starred_url": "https://api.github.com/users/roney1001/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/roney1001/subscriptions",
"organizations_url": "https://api.github.com/users/roney1001/orgs",
"repos_url": "https://api.github.com/users/roney1001/repos",
"events_url": "https://api.github.com/users/roney1001/events{/privacy}",
"received_events_url": "https://api.github.com/users/roney1001/received_events",
"type": "User",
"site_admin": false,
"name": "Abhishek Singh ",
"company": null,
"blog": "",
"location": null,
"email": null,
"hireable": null,
"bio": "creator and coding Addict",
"twitter_username": "abhishe52157504",
"public_repos": 7,
"public_gists": 0,
"followers": 2,
"following": 2,
"created_at": "2019-10-25T16:22:45Z",
"updated_at": "2022-03-13T13:35:14Z"
}
