export default [
{
"login": "Logicless-Coder",
"id": 59042344,
"node_id": "MDQ6VXNlcjU5MDQyMzQ0",
"avatar_url": "https://avatars.githubusercontent.com/u/59042344?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Logicless-Coder",
"html_url": "https://github.com/Logicless-Coder",
"followers_url": "https://api.github.com/users/Logicless-Coder/followers",
"following_url": "https://api.github.com/users/Logicless-Coder/following{/other_user}",
"gists_url": "https://api.github.com/users/Logicless-Coder/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Logicless-Coder/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Logicless-Coder/subscriptions",
"organizations_url": "https://api.github.com/users/Logicless-Coder/orgs",
"repos_url": "https://api.github.com/users/Logicless-Coder/repos",
"events_url": "https://api.github.com/users/Logicless-Coder/events{/privacy}",
"received_events_url": "https://api.github.com/users/Logicless-Coder/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Aditya-Gupta5",
"id": 59477517,
"node_id": "MDQ6VXNlcjU5NDc3NTE3",
"avatar_url": "https://avatars.githubusercontent.com/u/59477517?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Aditya-Gupta5",
"html_url": "https://github.com/Aditya-Gupta5",
"followers_url": "https://api.github.com/users/Aditya-Gupta5/followers",
"following_url": "https://api.github.com/users/Aditya-Gupta5/following{/other_user}",
"gists_url": "https://api.github.com/users/Aditya-Gupta5/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Aditya-Gupta5/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Aditya-Gupta5/subscriptions",
"organizations_url": "https://api.github.com/users/Aditya-Gupta5/orgs",
"repos_url": "https://api.github.com/users/Aditya-Gupta5/repos",
"events_url": "https://api.github.com/users/Aditya-Gupta5/events{/privacy}",
"received_events_url": "https://api.github.com/users/Aditya-Gupta5/received_events",
"type": "User",
"site_admin": false
}
];
